package com.mx.agroweb.cliente.dao;

import java.util.List;

import javax.sql.DataSource;

import com.mx.agroweb.cliente.vo.ClInsumosVO;
import com.mx.agroweb.cliente.vo.ClMaquinariaVO;

public interface ClMaquinariaDAO {

	public final String QUERY_INSERT = "INSERT INTO CAT_MAQUINARIA(MAQ_ID_GRUPO,MAQ_CODIGO,MAQ_DESCRIPCION,MAQ_ID_MARCA,MAQ_ANIO,MAQ_MODELO,MAQ_ID_PROPIETARIO,MAQ_NUM_SERIE,MAQ_NUM_TRANSMISION,MAQ_NUM_SERIE_MOTOR,MAQ_CAPACIDAD_MOTOR,MAQ_FECHA_COMPRA,MAQ_ID_RANCHO,MAQ_FOTO,MAQ_COSTO_HORA1,MAQ_COSTO_HORA2,MAQ_COSTO_HORA3,MAQ_COSTO_HORA4,MAQ_HOROMETRO_COMPRA,MAQ_HOROMETRO_INICIAL,MAQ_ID_TIPO_CAMBIO,MAQ_PEDIMIENTO_IMPORTACION,MAQ_ID_PROVEEDOR,MAQ_OBSERVACIONES,MAQ_FECHA_VENTA,MAQ_COMPRADOR,MAQ_PRECIO_VENTA,MAQ_PRECIO_COMPRA_PESOS,MAQ_PRECIO_COMPRA_DLLS,MAQ_FLETE_AMERICANO_PESOS,MAQ_FLETE_AMERICANO_DLLS,MAQ_COSTO_BROKER_PESOS,MAQ_COSTO_BROKER_DLLS,MAQ_ADUANALES_PESOS,MAQ_ADUANALES_DLLS,MAQ_IMPUESTOS_MEXICANOS_PESOS,MAQ_IMPUESTOS_MEXICANOS_DLLS,MAQ_FLETE_MEXICANO_PESOS,MAQ_FLETE_MEXICANO_DLLS,MAQ_SEGURO_PESOS,MAQ_SEGURO_DLLS,MAQ_OTROS_GASTOS_PESOS,MAQ_OTROS_GASTOS_DLLS) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)";
	public final String QUERY_GET_BY_ID = "SELECT * FROM CAT_MAQUINARIA WHERE BINARY ID = ?";
	public final String QUERY_GET_ALL = "SELECT * FROM CAT_MAQUINARIA";
	public final String QUERY_DELETE_BY_ID = "DELETE FROM CAT_MAQUINARIA WHERE BINARY ID = ?";
	public final String QUERY_UPDATE_BY_ID = "UPDATE MAQ_ID_GRUPO = ?,MAQ_CODIGO = ?,MAQ_DESCRIPCION = ?,MAQ_ID_MARCA = ?,MAQ_ANIO = ?,MAQ_MODELO = ?,MAQ_ID_PROPIETARIO = ?,MAQ_NUM_SERIE = ?,MAQ_NUM_TRANSMISION = ?,MAQ_NUM_SERIE_MOTOR = ?,MAQ_CAPACIDAD_MOTOR = ?,MAQ_FECHA_COMPRA = ?,MAQ_ID_RANCHO = ?,MAQ_FOTO = ?,MAQ_COSTO_HORA1 = ?,MAQ_COSTO_HORA2 = ?,MAQ_COSTO_HORA3 = ?,MAQ_COSTO_HORA4 = ?,MAQ_HOROMETRO_COMPRA = ?,MAQ_HOROMETRO_INICIAL = ?,MAQ_ID_TIPO_CAMBIO = ?,MAQ_PEDIMIENTO_IMPORTACION = ?,MAQ_ID_PROVEEDOR = ?,MAQ_OBSERVACIONES = ?,MAQ_FECHA_VENTA = ?,MAQ_COMPRADOR = ?,MAQ_PRECIO_VENTA = ?,MAQ_PRECIO_COMPRA_PESOS = ?,MAQ_PRECIO_COMPRA_DLLS = ?,MAQ_FLETE_AMERICANO_PESOS = ?,MAQ_FLETE_AMERICANO_DLLS = ?,MAQ_COSTO_BROKER_PESOS = ?,MAQ_COSTO_BROKER_DLLS = ?,MAQ_ADUANALES_PESOS = ?,MAQ_ADUANALES_DLLS = ?,MAQ_IMPUESTOS_MEXICANOS_PESOS = ?,MAQ_IMPUESTOS_MEXICANOS_DLLS = ?,MAQ_FLETE_MEXICANO_PESOS = ?,MAQ_FLETE_MEXICANO_DLLS = ?,MAQ_SEGURO_PESOS = ?,MAQ_SEGURO_DLLS = ?,MAQ_OTROS_GASTOS_PESOS = ?,MAQ_OTROS_GASTOS_DLLS = ? WHERE BINARY ID = ?;";

	public void insertMaquinaria(ClMaquinariaVO clMaquinariaVO);

	public ClMaquinariaVO getMaquinaria(int id);

	public List<ClMaquinariaVO> getMaquinarias();

	public void setDinamicDataSource(DataSource dataSource);

	public void deleteMaquinaria(int id);

	public void updateMaquinaria(ClMaquinariaVO clMaquinariaVO);

}
